version: '3.7'
services:
  http-server:
    environment:
      - UPTRACE_DSN
    build:
      dockerfile: $PWD/Dockerfile
      context: ../..
    ports:
      - '9999:9999'
    command:
      - '/bin/sh'
      - '-c'
      - '/go/bin/server'
