dist: xenial
language: go

go:
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip

go_import_path: github.com/uptrace/uptrace-go

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go
    env GOPATH)/bin v1.31.0
