[sources.in]
type = "file"
include = ["zerolog.log"]

[sinks.out]
type = "http"
inputs = ["in"]
encoding.codec = "json"
framing.method = "newline_delimited"
compression = "gzip"
uri = "https://api.uptrace.dev/api/v1/vector/logs"
request.headers.uptrace-dsn = "https://<token>@uptrace.dev/<project_id>"
